feat(git-hooks): add lint-php, lint-js and pre-commit scripts
elementor/elementor-editor-packages pull request #2
Opened 2020-11-25 14:59 UTC by Nevoss

2020-12-01 13:59 UTC, matipojo requested changes

2020-12-01 13:59 UTC, matipojo commented on packages/git-hooks/package.json
> +  "license": "MIT",
GPL3+

2020-12-01 13:59 UTC, matipojo commented on packages/git-hooks/rollup.config.js
> +module.exports = ({ path, plugins: { commonjs, shebang } }) => {
ESlint for all files.

2020-12-01 13:59 UTC, matipojo commented on packages/git-hooks/src/index.js
> +if (!optionalScripts.hasOwnProperty(scriptName)) {
Check has scripts.

2020-12-01 13:59 UTC, matipojo commented on packages/git-hooks/src/scripts/lint-js.js
> +	const lint = exec(`npm run lint -- ${files}`);
Catch the stdout/stderror and throw a relevant error.

2020-12-01 13:59 UTC, matipojo commented on packages/git-hooks/src/utils/logs.js
> +import chalk from 'chalk';
@efelementor Use it like here.

2020-12-06 13:54 UTC, matipojo requested changes

2020-12-06 13:54 UTC, matipojo commented on package-lock.json
>        },
Remove.

2020-12-07 09:30 UTC, matipojo approved these changes

2020-12-10 10:54 UTC, KingYes requested changes

2020-12-10 10:54 UTC, KingYes commented on packages/git-hooks/.gitignore
> +bin
```suggestion
bin/
```

2020-12-10 11:47 UTC, closed without merging